{
 "title": "zrepl",
 "tags": [
  "zfs",
  "zrepl",
  "sink_server"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   { "name": "prom_job_name", "label": "Prometheus Job Name", "query": { "query": "label_values(up,job)" } },
   {
    "name": "zrepl_job_name",
    "label": "Zrepl Job Name",
    "query": {
     "query": "label_values(zrepl_replication_filesystem_errors{job=\"$prom_job_name\"}, zrepl_job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(zrepl_start_time,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "zrepl Prometheus Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances Up",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(zrepl_start_time{job='$prom_job_name',instance=~'$instance'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replication Data Volume by Zrepl Job Name",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(zrepl_replication_bytes_replicated{job='$prom_job_name',instance=~'$instance'}[${__range_s}s])) by (zrepl_job)",
     "legendFormat": "{{zrepl_job}}"
    }
   ]
  },
  {
   "title": "Replication Data Volume by Instance",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(zrepl_replication_bytes_replicated{job='$prom_job_name',instance=~'$instance'}[${__range_s}s])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed Replications",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zrepl_replication_filesystem_errors{job=\"$prom_job_name\",instance=~'$instance'})",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{instance}}:$zrepl_job_name",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active tasks tracked by the zrepl trace module",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zrepl_trace_active_tasks{instance=~'$instance'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 10 Filesystem Replication Data Volume",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10,sum(increase(zrepl_replication_bytes_replicated{job=\"zfs-zrepl\",instance=~'$instance'}[${__range_s}s])) by (instance,filesystem))",
     "legendFormat": "{{instance}}:{{filesystem}}"
    }
   ]
  },
  {
   "title": "Log Messages that require attention (warning or error)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(zrepl_daemon_log_entries{job='$prom_job_name',instance=~'$instance',level=~'warn|error'}[${__range_s}s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Log Activity (without internal jobs)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(zrepl_daemon_log_entries{job='$prom_job_name',instance=~'$instance',zrepl_job=~\"^[^_].*\"}[1m])) by (instance,zrepl_job)",
     "legendFormat": "{{instance}} [job={{zrepl_job}}]"
    }
   ]
  },
  {
   "title": "Abstraction Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(zrepl_endpoint_abstractions_cache_entry_count{instance=~'$instance'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "zfs abstractions cache entry count (should not be zero and not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "zrepl_endpoint_abstractions_cache_entry_count{instance=~'$instance'}",
     "legendFormat": "{{instance}} [job={{job}}]"
    }
   ]
  },
  {
   "title": "Go Memory Allocations (should not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job='$prom_job_name',instance=~'$instance'}",
     "legendFormat": "{{instance}} [job={{job}}]"
    }
   ]
  },
  {
   "title": "number of goroutines (should not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job='$prom_job_name',instance=~'$instance'}",
     "legendFormat": "{{instance}} [job={{job}}]"
    }
   ]
  },
  {
   "title": "Memory Allocated by the Go runtime from the OS (should not grow unboundedly)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_sys_bytes{job='$prom_job_name',instance=~'$instance'}",
     "legendFormat": "{{instance}} [job={{job}}]"
    }
   ]
  }
 ]
}