---
global:
  control:
    sockpath: /var/run/zrepl/control
  logging:
    - type: stdout
      format: human
      level: info

jobs:
  - type: sink
    name: zrepl_sink_server
    root_fs: "zroot/zrepl_sink_data"
    serve:
      type: tls
      listen: ":8448"
      listen_freebind: true
      ca: /config/ca.crt
      cert: /config/sink-srv.crt
      key: /config/sink-srv.key
      client_cns:
        - "dldsk01"
        - "k3s01"
        - "k3s02"
        - "k3s03"
        - "k3s04"
        - "k3s05"
        - "k3s06"
    recv:
      properties:
        # Force mountpoint to be inherited from Sink container (set to none)
        inherit:
          - "mountpoint"
        override: {
          # These two need to be disabled to support ZVOL replication
          # "canmount": "off",
          # "mountpoint": "none"
          "readonly": "on",
          "openzfs.systemd:ignore": "on"
          }
      placeholder:
        encryption: inherit
